export const courses_input = [
  {
    codcurso: "EL4001",
    nombrecurso: "Circuitos Analógicos",
    r2: "0.892",
    area: "ELECTRONICA",
    prediccion: "13",
  },
  {
    codcurso: "EL5002",
    nombrecurso: "Análisis de Señales y Sistemas",
    r2: "0.982",
    area: "ELECTRONICA",
    prediccion: "96",
  },
  {
    codcurso: "EL4002",
    nombrecurso: "Modelado y Simulación",
    r2: "0.967",
    area: "ELECTRONICA",
    prediccion: "105",
  },
  {
    codcurso: "ME4003",
    nombrecurso: "Mecánica de Fluidos",
    r2: "0.937",
    area: "MECANICA",
    prediccion: "122",
  },
  {
    codcurso: "ME0003",
    nombrecurso: "Seguridad en operaciones mineras",
    r2: "0.843",
    area: "MECANICA",
    prediccion: "24",
  },
  {
    codcurso: "QI0003",
    nombrecurso: "Mineralogía Aplicada",
    r2: "0.946",
    area: "QUIMICA",
    prediccion: "17",
  },
  {
    codcurso: "EL6003",
    nombrecurso: "Control Automático",
    r2: "0.919",
    area: "ELECTRONICA",
    prediccion: "66",
  },
  {
    codcurso: "ME9002",
    nombrecurso: "Tesis en Ingeniería Mecánica I",
    r2: "0.947",
    area: "MECANICA",
    prediccion: "19",
  },
  {
    codcurso: "IN0002",
    nombrecurso: "Tesis en Ingeniería Industrial II",
    r2: "0.968",
    area: "INDUSTRIAL",
    prediccion: "20",
  },
  {
    codcurso: "ME6006",
    nombrecurso: "Mecánica de Materiales",
    r2: "0.987",
    area: "MECANICA",
    prediccion: "116",
  },
  {
    codcurso: "ME3003",
    nombrecurso: "Estática",
    r2: "0.814",
    area: "MECANICA",
    prediccion: "128",
  },
  {
    codcurso: "IN8006",
    nombrecurso: "Análisis y Diseño de Sistemas de Manufactura y Servicios",
    r2: "0.777",
    area: "INDUSTRIAL",
    prediccion: "61",
  },
  {
    codcurso: "ME0019",
    nombrecurso: "Física I",
    r2: "0.751",
    area: "CIENCIAS",
    prediccion: "383",
  },
  {
    codcurso: "EN0030",
    nombrecurso: "Biomasa y Geotermia",
    r2: "0.92",
    area: "ENERGIA",
    prediccion: "39",
  },
  {
    codcurso: "GH0009",
    nombrecurso: "Perú: ¿País Industrial?",
    r2: "0.828",
    area: "HACS",
    prediccion: "207",
  },
  {
    codcurso: "GH0017",
    nombrecurso: "Introducción al Quechua",
    r2: "0.617",
    area: "HACS",
    prediccion: "45",
  },
  {
    codcurso: "QI6006",
    nombrecurso: "Transferencia de masa",
    r2: "0.872",
    area: "QUIMICA",
    prediccion: "17",
  },
  {
    codcurso: "EL6004",
    nombrecurso: "Introducción a Sistemas Embebidos",
    r2: "0.972",
    area: "ELECTRONICA",
    prediccion: "44",
  },
  {
    codcurso: "EG0009",
    nombrecurso: "Proyecto Interdisciplinario III",
    r2: "0.911",
    area: "PIs",
    prediccion: "213",
  },
  {
    codcurso: "ME0028",
    nombrecurso: "Automatización de Sistemas",
    r2: "0.948",
    area: "MECANICA",
    prediccion: "60",
  },
  {
    codcurso: "ME0004",
    nombrecurso: "Tesis en Ingeniería Mecánica II",
    r2: "0.967",
    area: "MECANICA",
    prediccion: "28",
  },
  {
    codcurso: "ME0022",
    nombrecurso: "Dinámica",
    r2: "0.823",
    area: "MECANICA",
    prediccion: "67",
  },
  {
    codcurso: "GH1002",
    nombrecurso: "Arte y Tecnología",
    r2: "0.835",
    area: "HACS",
    prediccion: "328",
  },
  {
    codcurso: "EN0028",
    nombrecurso: "Tesis en Ingeniería de la Energía II",
    r2: "0.86",
    area: "ENERGIA",
    prediccion: "7",
  },
  {
    codcurso: "QI0030",
    nombrecurso: "Procesos Químicos en la Industria",
    r2: "0.117",
    area: "QUIMICA",
    prediccion: "13",
  },
  {
    codcurso: "EN0024",
    nombrecurso: "Marco Legal y Politica Energética",
    r2: "0.992",
    area: "ENERGIA",
    prediccion: "19",
  },
  {
    codcurso: "EN8004",
    nombrecurso: "Auditoría y Eficiencia Energética",
    r2: "0.931",
    area: "ENERGIA",
    prediccion: "31",
  },
  {
    codcurso: "IN0074",
    nombrecurso: "Diseño de Redes de Cadenas de Suministro",
    r2: "0.517",
    area: "INDUSTRIAL",
    prediccion: "12",
  },
  {
    codcurso: "IN0076",
    nombrecurso: "Gestión de Centros de Distribución y Transporte",
    r2: "0.931",
    area: "INDUSTRIAL",
    prediccion: "48",
  },
  {
    codcurso: "GH0011",
    nombrecurso: "Innovación y Desarrollo de Productos",
    r2: "0.979",
    area: "GESTION",
    prediccion: "249",
  },
  {
    codcurso: "IN5005",
    nombrecurso: "Costeo de Operaciones",
    r2: "0.893",
    area: "INDUSTRIAL",
    prediccion: "47",
  },
  {
    codcurso: "EL6006",
    nombrecurso: "Electrónica de Potencia",
    r2: "0.997",
    area: "ELECTRONICA",
    prediccion: "13",
  },
  {
    codcurso: "IN0081",
    nombrecurso: "Modelado y Simulación de Procesos de Negocio",
    r2: "0.913",
    area: "INDUSTRIAL",
    prediccion: "53",
  },
  {
    codcurso: "IN0078",
    nombrecurso: "Gestión de Inventarios",
    r2: "0.698",
    area: "INDUSTRIAL",
    prediccion: "25",
  },
  {
    codcurso: "GH0019",
    nombrecurso: "Emprendedores en Acción",
    r2: "0.923",
    area: "HACS",
    prediccion: "50",
  },
  {
    codcurso: "EN5002",
    nombrecurso: "Ingeniería del Gas Natural",
    r2: "0.667",
    area: "ENERGIA",
    prediccion: "10",
  },
  {
    codcurso: "EG0003",
    nombrecurso: "Matemáticas I",
    r2: "0.638",
    area: "CIENCIAS",
    prediccion: "432",
  },
  {
    codcurso: "GH0015",
    nombrecurso: "Imagen y Marca Personal",
    r2: "0.884",
    area: "HACS",
    prediccion: "175",
  },
  {
    codcurso: "IN0082",
    nombrecurso: "Planeamiento de la Demanda",
    r2: "0.949",
    area: "INDUSTRIAL",
    prediccion: "38",
  },
  {
    codcurso: "ME0021",
    nombrecurso: "Termodinámica",
    r2: "0.895",
    area: "CIENCIAS",
    prediccion: "329",
  },
  {
    codcurso: "IN0056",
    nombrecurso: "Investigación de Operaciones I: Modelos Determinísticos",
    r2: "0.952",
    area: "INDUSTRIAL",
    prediccion: "91",
  },
  {
    codcurso: "ME0023",
    nombrecurso: "Dibujo y Diseño para Ingeniería",
    r2: "0.82",
    area: "MECANICA",
    prediccion: "101",
  },
  {
    codcurso: "IN0057",
    nombrecurso: "Seguridad y Salud Ocupacional",
    r2: "0.84",
    area: "INDUSTRIAL",
    prediccion: "168",
  },
  {
    codcurso: "GH0014",
    nombrecurso: "Culturas de Gobernanza y Distribución de Poder",
    r2: "0.986",
    area: "HACS",
    prediccion: "222",
  },
  {
    codcurso: "EL0045",
    nombrecurso: "Introducción a las Redes de Computadoras",
    r2: "0.959",
    area: "ELECTRONICA",
    prediccion: "28",
  },
  {
    codcurso: "EL7006",
    nombrecurso: "Instrumentación industrial",
    r2: "0.912",
    area: "ELECTRONICA",
    prediccion: "18",
  },
  {
    codcurso: "ME0026",
    nombrecurso: "Diseño de Sistemas Mecánicos",
    r2: "0.948",
    area: "MECANICA",
    prediccion: "19",
  },
  {
    codcurso: "ME0008",
    nombrecurso: "Gestión de Equipos y Maquinarias",
    r2: "0.885",
    area: "MECANICA",
    prediccion: "39",
  },
  {
    codcurso: "CS1102",
    nombrecurso: "Programación orientada a objetos I",
    r2: "0.92",
    area: "CIENCIAS",
    prediccion: "331",
  },
  {
    codcurso: "EL0069",
    nombrecurso: "Proyecto de ECE",
    r2: "0.756",
    area: "ELECTRONICA",
    prediccion: "14",
  },
  {
    codcurso: "IN0062",
    nombrecurso: "Diseño de Productos y Servicios",
    r2: "0.557",
    area: "INDUSTRIAL",
    prediccion: "50",
  },
  {
    codcurso: "EL0070",
    nombrecurso: "Tesis en ECE I",
    r2: "0.874",
    area: "ELECTRONICA",
    prediccion: "8",
  },
  {
    codcurso: "EG0006",
    nombrecurso: "Matemáticas III",
    r2: "0.756",
    area: "CIENCIAS",
    prediccion: "296",
  },
  {
    codcurso: "GH0006",
    nombrecurso: "Laboratorio de Comunicación 2",
    r2: "0.932",
    area: "HACS",
    prediccion: "379",
  },
  {
    codcurso: "CS1100",
    nombrecurso: "Introducción a la Ciencia de la Computación",
    r2: "0.337",
    area: "CIENCIAS",
    prediccion: "366",
  },
  {
    codcurso: "AM0040",
    nombrecurso: "Ecosistemas y Paisajes",
    r2: "0.699",
    area: "AMBIENTAL",
    prediccion: "13",
  },
  {
    codcurso: "EN0038",
    nombrecurso: "Energía Eólica",
    r2: "0.862",
    area: "ENERGIA",
    prediccion: "29",
  },
  {
    codcurso: "ME0036",
    nombrecurso: "Tópicos Selectos de Ingeniería Mecánica",
    r2: "0.521",
    area: "MECANICA",
    prediccion: "10",
  },
  {
    codcurso: "MT0002",
    nombrecurso: "Sensores y Actuadores",
    r2: "0.987",
    area: "MECATRONICA",
    prediccion: "40",
  },
  {
    codcurso: "CS2701",
    nombrecurso: "Base de datos I",
    r2: "0.947",
    area: "CS",
    prediccion: "50",
  },
  {
    codcurso: "EN4003",
    nombrecurso: "Ingeniería del Petróleo",
    r2: "0.82",
    area: "ENERGIA",
    prediccion: "19",
  },
  {
    codcurso: "AM0001",
    nombrecurso: "Introducción a la Ingeniería Ambiental",
    r2: "0.467",
    area: "AMBIENTAL",
    prediccion: "47",
  },
  {
    codcurso: "EN0027",
    nombrecurso: "Tesis en Ingenieria de la Energía I",
    r2: "0.791",
    area: "ENERGIA",
    prediccion: "7",
  },
  {
    codcurso: "QI7005",
    nombrecurso: "Termodinámica Química",
    r2: "0.824",
    area: "QUIMICA",
    prediccion: "10",
  },
  {
    codcurso: "EG0008",
    nombrecurso: "Proyecto Interdisciplinario II",
    r2: "0.605",
    area: "PIs",
    prediccion: "283",
  },
  {
    codcurso: "EN0021",
    nombrecurso: "Física II",
    r2: "0.961",
    area: "CIENCIAS",
    prediccion: "380",
  },
  {
    codcurso: "GH0025",
    nombrecurso: "English for STEAM",
    r2: "0.977",
    area: "HACS",
    prediccion: "149",
  },
  {
    codcurso: "QI0027",
    nombrecurso: "Química General",
    r2: "0.633",
    area: "CIENCIAS",
    prediccion: "511",
  },
  {
    codcurso: "AM0037",
    nombrecurso: "Ciencia de los Materiales",
    r2: "0.99",
    area: "CIENCIAS",
    prediccion: "251",
  },
  {
    codcurso: "IN0065",
    nombrecurso: "Simulación de Operaciones",
    r2: "0.625",
    area: "INDUSTRIAL",
    prediccion: "58",
  },
  {
    codcurso: "IN0067",
    nombrecurso: "Sistemas de Información para Operaciones",
    r2: "0.998",
    area: "INDUSTRIAL",
    prediccion: "12",
  },
  {
    codcurso: "GH0008",
    nombrecurso: "Gestión de Empresas",
    r2: "0.733",
    area: "GESTION",
    prediccion: "342",
  },
  {
    codcurso: "GH0007",
    nombrecurso: "Introducción al Desarrollo de Empresas",
    r2: "0.954",
    area: "GESTION",
    prediccion: "342",
  },
  {
    codcurso: "EN0025",
    nombrecurso: "Planificación y Economía de la Energía",
    r2: "0.66",
    area: "ENERGIA",
    prediccion: "33",
  },
  {
    codcurso: "QI0001",
    nombrecurso: "Tesis en Ingeniería Química II",
    r2: "0.438",
    area: "QUIMICA",
    prediccion: "9",
  },
  {
    codcurso: "QI0040",
    nombrecurso: "Diseño de Reactores Químicos I",
    r2: "0.629",
    area: "QUIMICA",
    prediccion: "7",
  },
  {
    codcurso: "CS2901",
    nombrecurso: "Ingeniería de Software I",
    r2: "0.965",
    area: "CS",
    prediccion: "49",
  },
  {
    codcurso: "GH0024",
    nombrecurso: "Crítica de la Modernidad",
    r2: "0.997",
    area: "HACS",
    prediccion: "195",
  },
  {
    codcurso: "IN0063",
    nombrecurso: "Lean Thinking",
    r2: "0.991",
    area: "INDUSTRIAL",
    prediccion: "29",
  },
  {
    codcurso: "ME0035",
    nombrecurso: "Seminario de proyecto pre profesional",
    r2: "0.945",
    area: "MECANICA",
    prediccion: "25",
  },
  {
    codcurso: "CS1D01",
    nombrecurso: "Estructuras Discretas I",
    r2: "0.021",
    area: "CS",
    prediccion: "89",
  },
  {
    codcurso: "IN0060",
    nombrecurso: "Planeamiento y Control de Operaciones",
    r2: "0.922",
    area: "INDUSTRIAL",
    prediccion: "39",
  },
  {
    codcurso: "ME0037",
    nombrecurso: "Ingeniería de Materiales",
    r2: "0.911",
    area: "MECANICA",
    prediccion: "21",
  },
  {
    codcurso: "IN0061",
    nombrecurso: "Investigación de Operaciones II: Modelos Probabilísticos",
    r2: "0.627",
    area: "INDUSTRIAL",
    prediccion: "68",
  },
  {
    codcurso: "AM0012",
    nombrecurso: '"Atmosfera',
    r2: ' oceano y dinamica climatica"',
    area: "0.108",
    prediccion: "AMBIENTAL",
  },
  {
    codcurso: "AM0038",
    nombrecurso: "Hidrología",
    r2: "1.0",
    area: "AMBIENTAL",
    prediccion: "13",
  },
  {
    codcurso: "EN0022",
    nombrecurso: "Hidroenergía",
    r2: "0.689",
    area: "ENERGIA",
    prediccion: "16",
  },
  {
    codcurso: "CS2702",
    nombrecurso: "Base de datos II",
    r2: "0.958",
    area: "CS",
    prediccion: "23",
  },
  {
    codcurso: "QI6005",
    nombrecurso: "Transferencia de calor",
    r2: "0.953",
    area: "QUIMICA",
    prediccion: "68",
  },
  {
    codcurso: "EN7003",
    nombrecurso: "Máquinas Térmicas",
    r2: "0.866",
    area: "ENERGIA",
    prediccion: "30",
  },
  {
    codcurso: "QI0033",
    nombrecurso: "Análisis Químico para Ingeniería",
    r2: "0.892",
    area: "QUIMICA",
    prediccion: "5",
  },
  {
    codcurso: "BI0036",
    nombrecurso: "Ciencia y Cocina",
    r2: "0.481",
    area: "BIO",
    prediccion: "20",
  },
  {
    codcurso: "IN9001",
    nombrecurso: "Tesis en Ingeniería Industrial I",
    r2: "0.831",
    area: "INDUSTRIAL",
    prediccion: "20",
  },
  {
    codcurso: "EL8005",
    nombrecurso: "Redes industriales",
    r2: "0.503",
    area: "ELECTRONICA",
    prediccion: "11",
  },
  {
    codcurso: "IN0054",
    nombrecurso: "Estadística y Probabilidades",
    r2: "0.69",
    area: "CIENCIAS",
    prediccion: "228",
  },
  {
    codcurso: "AM0010",
    nombrecurso: "Geologia General",
    r2: "0.879",
    area: "AMBIENTAL",
    prediccion: "47",
  },
  {
    codcurso: "BI0024",
    nombrecurso: "Biodiseño",
    r2: "0.833",
    area: "BIO",
    prediccion: "40",
  },
  {
    codcurso: "CS2201",
    nombrecurso: "Arquitectura de computadoras",
    r2: "0.83",
    area: "CS",
    prediccion: "77",
  },
  {
    codcurso: "CS2B01",
    nombrecurso: "Desarrollo basado en plataformas",
    r2: "0.658",
    area: "CS",
    prediccion: "59",
  },
  {
    codcurso: "CS3101",
    nombrecurso: "Programación Competitiva",
    r2: "1.0",
    area: "CS",
    prediccion: "29",
  },
  {
    codcurso: "MT0006",
    nombrecurso: "Fundamentos de Robótica",
    r2: "0.994",
    area: "MECATRONICA",
    prediccion: "17",
  },
  {
    codcurso: "EG0005",
    nombrecurso: "Matemáticas II",
    r2: "0.943",
    area: "CIENCIAS",
    prediccion: "368",
  },
  {
    codcurso: "AM0015",
    nombrecurso: "Desarrollo sustentable",
    r2: "1.0",
    area: "AMBIENTAL",
    prediccion: "26",
  },
  {
    codcurso: "MT0001",
    nombrecurso: "Mecanismos y Transmisión de Movimiento",
    r2: "0.713",
    area: "MECATRONICA",
    prediccion: "31",
  },
  {
    codcurso: "CS1103",
    nombrecurso: "Programación orientada a objetos II",
    r2: "0.913",
    area: "CS",
    prediccion: "76",
  },
  {
    codcurso: "BI0016",
    nombrecurso: "Robótica médica",
    r2: "0.548",
    area: "BIO",
    prediccion: "3",
  },
  {
    codcurso: "CS2601",
    nombrecurso: "Inteligencia Artificial",
    r2: "1.0",
    area: "CS",
    prediccion: "34",
  },
  {
    codcurso: "BI0005",
    nombrecurso: "Biotransporte",
    r2: "0.998",
    area: "BIO",
    prediccion: "27",
  },
  {
    codcurso: "BI0001",
    nombrecurso: "Química Orgánica",
    r2: "0.614",
    area: "BIO",
    prediccion: "54",
  },
  {
    codcurso: "QI0042",
    nombrecurso: "Operaciones de Separación Físico-Mecánicas",
    r2: "0.692",
    area: "QUIMICA",
    prediccion: "13",
  },
  {
    codcurso: "CI0004",
    nombrecurso: "Geomática",
    r2: "0.994",
    area: "CIVIL",
    prediccion: "36",
  },
  {
    codcurso: "EN3004",
    nombrecurso: "Ingeniería Eléctrica",
    r2: "0.791",
    area: "ENERGIA",
    prediccion: "13",
  },
  {
    codcurso: "IN0090",
    nombrecurso: "Ingeniería Financiera",
    r2: "0.969",
    area: "INDUSTRIAL",
    prediccion: "49",
  },
  {
    codcurso: "BI0025",
    nombrecurso: "Bioinformática y Bioestadística",
    r2: "0.572",
    area: "BIO",
    prediccion: "26",
  },
  {
    codcurso: "IN0059",
    nombrecurso: "Diseño de Experimentos y Control Estadístico de Procesos",
    r2: "0.435",
    area: "INDUSTRIAL",
    prediccion: "22",
  },
  {
    codcurso: "GH0016",
    nombrecurso: "Liderazgo y negociación",
    r2: "0.961",
    area: "GESTION",
    prediccion: "135",
  },
  {
    codcurso: "CI0008",
    nombrecurso: "Tecnología de los Materiales de Construcción",
    r2: "1.0",
    area: "CIVIL",
    prediccion: "13",
  },
  {
    codcurso: "AM0004",
    nombrecurso: "Ecología y Recursos Naturales",
    r2: "0.989",
    area: "AMBIENTAL",
    prediccion: "52",
  },
  {
    codcurso: "QI0037",
    nombrecurso: "Diseño de Procesos Químicos",
    r2: "1.0",
    area: "QUIMICA",
    prediccion: "18",
  },
  {
    codcurso: "MT0008",
    nombrecurso: "Diseño de sistemas mecatrónicos",
    r2: "0.818",
    area: "MECATRONICA",
    prediccion: "11",
  },
  {
    codcurso: "CS3903",
    nombrecurso: "Sistemas de Información",
    r2: "0.69",
    area: "CS",
    prediccion: "31",
  },
  {
    codcurso: "CS2102",
    nombrecurso: "Análisis y Diseño de Algoritmos-ADA",
    r2: "0.604",
    area: "CS",
    prediccion: "41",
  },
  {
    codcurso: "BI0002",
    nombrecurso: "Biología Celular y Molecular",
    r2: "0.894",
    area: "BIO",
    prediccion: "36",
  },
  {
    codcurso: "CI0009",
    nombrecurso: "Resistencia de Materiales II",
    r2: "1.0",
    area: "CIVIL",
    prediccion: "10",
  },
  {
    codcurso: "GH0033",
    nombrecurso: "Discapacidad: Los Retos de la Inclusión",
    r2: "0.617",
    area: "HACS",
    prediccion: "32",
  },
  {
    codcurso: "BI0003",
    nombrecurso: "Fundamentos de Bioingeniería",
    r2: "0.924",
    area: "BIO",
    prediccion: "37",
  },
  {
    codcurso: "CI0007",
    nombrecurso: "Geodesia Satelital y Fotogrametría",
    r2: "1.0",
    area: "CIVIL",
    prediccion: "15",
  },
  {
    codcurso: "QI0031",
    nombrecurso: "Química Orgánica Aplicada",
    r2: "0.903",
    area: "QUIMICA",
    prediccion: "11",
  },
  {
    codcurso: "EG0013",
    nombrecurso: "Proyecto Preprofesional",
    r2: "1.0",
    area: "PIs",
    prediccion: "122",
  },
  {
    codcurso: "EN5001",
    nombrecurso: "Máquinas Eléctricas ",
    r2: "0.969",
    area: "ENERGIA",
    prediccion: "35",
  },
  {
    codcurso: "EN0020",
    nombrecurso: "Smart Grid",
    r2: "0.971",
    area: "ENERGIA",
    prediccion: "25",
  },
  {
    codcurso: "EL0042",
    nombrecurso: "Supervisión y Control por Computadora",
    r2: "0.97",
    area: "ELECTRONICA",
    prediccion: "18",
  },
  {
    codcurso: "EL0046",
    nombrecurso: "Ingeniería Electromagnética",
    r2: "0.573",
    area: "ELECTRONICA",
    prediccion: "12",
  },
  {
    codcurso: "EG0004",
    nombrecurso: "Desafíos Globales",
    r2: "0.192",
    area: "HACS",
    prediccion: "276",
  },
  {
    codcurso: "GH0005",
    nombrecurso: "Laboratorio de Comunicación 1",
    r2: "0.53",
    area: "HACS",
    prediccion: "216",
  },
  {
    codcurso: "IN0077",
    nombrecurso: "Gestión de Compras y Mercados Electrónicos",
    r2: "0.921",
    area: "INDUSTRIAL",
    prediccion: "57",
  },
  {
    codcurso: "GH0012",
    nombrecurso: "Economías en Desarrollo",
    r2: "0.937",
    area: "HACS",
    prediccion: "197",
  },
  {
    codcurso: "IN0075",
    nombrecurso: "Diseño y Gestión de Servicios",
    r2: "0.914",
    area: "INDUSTRIAL",
    prediccion: "48",
  },
  {
    codcurso: "EL5005",
    nombrecurso: "Diseño de Computadoras",
    r2: "0.761",
    area: "ELECTRONICA",
    prediccion: "38",
  },
  {
    codcurso: "QI0029",
    nombrecurso: "Química Avanzada",
    r2: "0.461",
    area: "QUIMICA",
    prediccion: "16",
  },
  {
    codcurso: "EL0071",
    nombrecurso: "Tesis en ECE II",
    r2: "0.74",
    area: "ELECTRONICA",
    prediccion: "12",
  },
  {
    codcurso: "QI0034",
    nombrecurso: "Biotecnologías y Bioprocesos",
    r2: "0.297",
    area: "QUIMICA",
    prediccion: "12",
  },
  {
    codcurso: "EL7005",
    nombrecurso: "Control de procesos",
    r2: "0.784",
    area: "ELECTRONICA",
    prediccion: "28",
  },
  {
    codcurso: "CS2101",
    nombrecurso: "Teoría de la computación",
    r2: "0.827",
    area: "CS",
    prediccion: "34",
  },
  {
    codcurso: "IN0058",
    nombrecurso: "Procesos de Manufactura",
    r2: "0.848",
    area: "INDUSTRIAL",
    prediccion: "63",
  },
  {
    codcurso: "EL0065",
    nombrecurso: "Circuitos Eléctricos",
    r2: "0.806",
    area: "ELECTRONICA",
    prediccion: "16",
  },
  {
    codcurso: "EG0007",
    nombrecurso: "Proyecto Interdisciplinario I",
    r2: "0.495",
    area: "PIs",
    prediccion: "257",
  },
  {
    codcurso: "IN0066",
    nombrecurso: "Métodos Estadísticos Avanzados para la Calidad",
    r2: "0.85",
    area: "INDUSTRIAL",
    prediccion: "17",
  },
  {
    codcurso: "EG0011",
    nombrecurso: "Proyecto Interdisciplinario IV",
    r2: "0.988",
    area: "INDUSTRIAL",
    prediccion: "5",
  },
  {
    codcurso: "MT0003",
    nombrecurso: "Sistemas Hidráulicos y Neumáticos",
    r2: "0.693",
    area: "MECATRONICA",
    prediccion: "44",
  },
  {
    codcurso: "GH0010",
    nombrecurso: "Ética y tecnología",
    r2: "0.85",
    area: "HACS",
    prediccion: "204",
  },
  {
    codcurso: "ME0025",
    nombrecurso: "Diseño de Elementos de Máquinas",
    r2: "0.639",
    area: "MECANICA",
    prediccion: "32",
  },
  {
    codcurso: "ME0001",
    nombrecurso: "Introducción a la Ingeniería de Minas",
    r2: "0.94",
    area: "MECANICA",
    prediccion: "42",
  },
  {
    codcurso: "EN0039",
    nombrecurso: "Energía Solar y Termosolar",
    r2: "1.0",
    area: "ENERGIA",
    prediccion: "12",
  },
  {
    codcurso: "CS2S01",
    nombrecurso: "Sistemas Operativos",
    r2: "0.789",
    area: "CS",
    prediccion: "52",
  },
  {
    codcurso: "BI0004",
    nombrecurso: "Bioquímica",
    r2: "0.97",
    area: "BIO",
    prediccion: "27",
  },
  {
    codcurso: "AM0002",
    nombrecurso: "Fisica y quimica ambiental",
    r2: "0.945",
    area: "AMBIENTAL",
    prediccion: "14",
  },
  {
    codcurso: "CS1D02",
    nombrecurso: "Estructuras Discretas II",
    r2: "0.93",
    area: "CS",
    prediccion: "64",
  },
  {
    codcurso: "IN0068",
    nombrecurso: "Metodología de Investigación",
    r2: "0.719",
    area: "INDUSTRIAL",
    prediccion: "48",
  },
  {
    codcurso: "QI0043",
    nombrecurso: "Operaciones de Separación Fisicoquímicas",
    r2: "0.938",
    area: "QUIMICA",
    prediccion: "11",
  },
  {
    codcurso: "CS3402",
    nombrecurso: "Compiladores",
    r2: "0.695",
    area: "CS",
    prediccion: "15",
  },
  {
    codcurso: "EG0014",
    nombrecurso: "Tesis I",
    r2: "0.999",
    area: "Dirección Académica",
    prediccion: "231",
  },
  {
    codcurso: "IN0064",
    nombrecurso: "Logística y Gestión de la Cadena de Suministros",
    r2: "0.679",
    area: "INDUSTRIAL",
    prediccion: "53",
  },
  {
    codcurso: "IN0069",
    nombrecurso: "Métodos de Teoría de Decisiones",
    r2: "0.896",
    area: "INDUSTRIAL",
    prediccion: "57",
  },
  {
    codcurso: "EL0066",
    nombrecurso: "Circuitos Eléctricos y Analógicos",
    r2: "0.93",
    area: "ELECTRONICA",
    prediccion: "77",
  },
  {
    codcurso: "AM0039",
    nombrecurso: "Microbiologia Ambiental",
    r2: "1.0",
    area: "AMBIENTAL",
    prediccion: "15",
  },
  {
    codcurso: "AM0005",
    nombrecurso: '"Edafologia',
    r2: ' manejo y conservacion de suelos"',
    area: "1.0",
    prediccion: "AMBIENTAL",
  },
  {
    codcurso: "CS2100",
    nombrecurso: "Algoritmos y Estructura de datos",
    r2: "0.759",
    area: "CS",
    prediccion: "57",
  },
  {
    codcurso: "BI0026",
    nombrecurso: "Biomateriales",
    r2: "1.0",
    area: "BIO",
    prediccion: "56",
  },
  {
    codcurso: "QI0045",
    nombrecurso: "Control de Procesos Químicos",
    r2: "1.0",
    area: "QUIMICA",
    prediccion: "5",
  },
  {
    codcurso: "AM0011",
    nombrecurso: "Leyes y derechos ambientales",
    r2: "1.0",
    area: "AMBIENTAL",
    prediccion: "35",
  },
  {
    codcurso: "BI0027",
    nombrecurso: "Biomecánica",
    r2: "0.959",
    area: "BIO",
    prediccion: "20",
  },
  {
    codcurso: "CI0001",
    nombrecurso: "Introducción a la Ingeniería Civil",
    r2: "0.969",
    area: "CIVIL",
    prediccion: "62",
  },
  {
    codcurso: "ME0038",
    nombrecurso: "Tesis II",
    r2: "1.0",
    area: "MECANICA",
    prediccion: "11",
  },
  {
    codcurso: "QI0046",
    nombrecurso: "Tesis II",
    r2: "1.0",
    area: "QUIMICA",
    prediccion: "4",
  },
  {
    codcurso: "QI0044",
    nombrecurso: "Seminario en Ingeniería Química",
    r2: "0.998",
    area: "QUIMICA",
    prediccion: "10",
  },
  {
    codcurso: "AM0014",
    nombrecurso: "Monitoreo ambiental",
    r2: "1.0",
    area: "AMBIENTAL",
    prediccion: "16",
  },
  {
    codcurso: "CI0006",
    nombrecurso: "Resistencia de Materiales I",
    r2: "1.0",
    area: "CIVIL",
    prediccion: "21",
  },
  {
    codcurso: "CI0003",
    nombrecurso: "Tecnologías Aplicadas y Mega Proyectos en Ingeniería Civil",
    r2: "0.985",
    area: "CIVIL",
    prediccion: "28",
  },
  {
    codcurso: "EL4003",
    nombrecurso: "Circuitos Digitales",
    r2: "0.874",
    area: "ELECTRONICA",
    prediccion: "71",
  },
  {
    codcurso: "EL9002",
    nombrecurso: "Introducción a Cognitive Computing",
    r2: "0.999",
    area: "ELECTRONICA",
    prediccion: "18",
  },
  {
    codcurso: "CI0002",
    nombrecurso: "Geometría Descriptiva",
    r2: "0.899",
    area: "CIVIL",
    prediccion: "37",
  },
  {
    codcurso: "CS3102",
    nombrecurso: "Estructura de datos avanzados",
    r2: "0.893",
    area: "CS",
    prediccion: "34",
  },
  {
    codcurso: "CS2H01",
    nombrecurso: "Interacción Humano Computador",
    r2: "0.666",
    area: "CS",
    prediccion: "4",
  },
  {
    codcurso: "QI0028",
    nombrecurso: "Química Experimental",
    r2: "0.455",
    area: "CIENCIAS",
    prediccion: "120",
  },
  {
    codcurso: "CS3P01",
    nombrecurso: "Computación paralela y distribuida",
    r2: "1.0",
    area: "CS",
    prediccion: "44",
  },
  {
    codcurso: "ME0027",
    nombrecurso: "Ingeniería de Mantenimiento",
    r2: "1.0",
    area: "MECANICA",
    prediccion: "36",
  },
  {
    codcurso: "QI0032",
    nombrecurso: "Análisis de Procesos Químicos",
    r2: "0.758",
    area: "QUIMICA",
    prediccion: "13",
  },
  {
    codcurso: "EN0040",
    nombrecurso: "Tesis II",
    r2: "1.0",
    area: "ENERGIA",
    prediccion: "9",
  },
  {
    codcurso: "IN0083",
    nombrecurso: "Servicios Electrónicos",
    r2: "1.0",
    area: "INDUSTRIAL",
    prediccion: "14",
  },
  {
    codcurso: "BI0006",
    nombrecurso: "Fisiología y Fisiopatología",
    r2: "1.0",
    area: "BIO",
    prediccion: "62",
  },
  {
    codcurso: "CI0010",
    nombrecurso: "Diseño de Infraestructura",
    r2: "1.0",
    area: "CIVIL",
    prediccion: "7",
  },
  {
    codcurso: "CS3700",
    nombrecurso: "Big Data",
    r2: "1.0",
    area: "CS",
    prediccion: "17",
  },
  {
    codcurso: "CS2301",
    nombrecurso: "Redes y Comunicaciones",
    r2: "0.982",
    area: "CS",
    prediccion: "11",
  },
  {
    codcurso: "BI0019",
    nombrecurso: "Procesos de Biotecnología I",
    r2: "0.792",
    area: "BIO",
    prediccion: "12",
  },
  {
    codcurso: "AM0035",
    nombrecurso: "Principios de Teledetección y aplicaciones ambientales",
    r2: "1.0",
    area: "AMBIENTAL",
    prediccion: "20",
  },
  {
    codcurso: "ME0009",
    nombrecurso: "Análisis de Falla y Toma de Decisiones",
    r2: "0.973",
    area: "MECANICA",
    prediccion: "43",
  },
  {
    codcurso: "EL0078",
    nombrecurso: "Técnicas en Redes IP",
    r2: "0.991",
    area: "ELECTRONICA",
    prediccion: "5",
  },
  {
    codcurso: "AM0007",
    nombrecurso: "Ingenieria de residuos sólidos y gestión",
    r2: "1.0",
    area: "AMBIENTAL",
    prediccion: "18",
  },
  {
    codcurso: "GH0023",
    nombrecurso: "Business Communication",
    r2: "0.839",
    area: "HACS",
    prediccion: "125",
  },
  {
    codcurso: "QI0041",
    nombrecurso: "Diseño de Reactores Químicos II",
    r2: "1.0",
    area: "QUIMICA",
    prediccion: "5",
  },
  {
    codcurso: "MT0013",
    nombrecurso: "Robótica Autónoma",
    r2: "1.0",
    area: "MECATRONICA",
    prediccion: "39",
  },
  {
    codcurso: "IN0055",
    nombrecurso: "Ingeniería de Operaciones",
    r2: "0.298",
    area: "INDUSTRIAL",
    prediccion: "39",
  },
  {
    codcurso: "EL0085",
    nombrecurso: "Tesis II",
    r2: "1.0",
    area: "ELECTRONICA",
    prediccion: "10",
  },
  {
    codcurso: "BI0035",
    nombrecurso: "Bioinformática Avanzada",
    r2: "1.0",
    area: "BIO",
    prediccion: "9",
  },
  {
    codcurso: "BI0029",
    nombrecurso: "Sistemas Biológicos",
    r2: "1.0",
    area: "BIO",
    prediccion: "35",
  },
  {
    codcurso: "CI0011",
    nombrecurso: "Ingeniería de Transporte I",
    r2: "1.0",
    area: "CIVIL",
    prediccion: "1",
  },
  {
    codcurso: "AM0009",
    nombrecurso: "Hidrogeologia",
    r2: "1.0",
    area: "AMBIENTAL",
    prediccion: "8",
  },
  {
    codcurso: "CS4002",
    nombrecurso: "Proyecto Final de Carrera I",
    r2: "1.0",
    area: "CS",
    prediccion: "28",
  },
  {
    codcurso: "CI0005",
    nombrecurso: "Dinámica",
    r2: "1.0",
    area: "CIVIL",
    prediccion: "3",
  },
  {
    codcurso: "BI0023",
    nombrecurso: "Neurociencias",
    r2: "1.0",
    area: "BIO",
    prediccion: "22",
  },
  {
    codcurso: "AM0017",
    nombrecurso: "Contaminacion Atmosferica",
    r2: "1.0",
    area: "AMBIENTAL",
    prediccion: "7",
  },
  {
    codcurso: "CI0012",
    nombrecurso: "Mecánica de Suelos",
    r2: "1.0",
    area: "CIVIL",
    prediccion: "3",
  },
];
